"""milestone 1 core schema

Revision ID: 619d7ffb31a9
Revises: 
Create Date: 2026-07-25 20:53:18.800869

"""
from alembic import op
import sqlalchemy as sa


revision = '619d7ffb31a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=True),
    sa.Column('primary_phone', sa.String(length=50), nullable=True),
    sa.Column('normalized_phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('normalized_domain', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=12), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('source_id', sa.String(length=200), nullable=True),
    sa.Column('lead_status', sa.String(length=30), nullable=False),
    sa.Column('enrichment_status', sa.String(length=30), nullable=False),
    sa.Column('do_not_call', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.create_index(op.f('ix_businesses_do_not_call'), 'businesses', ['do_not_call'], unique=False)
    op.create_index(op.f('ix_businesses_enrichment_status'), 'businesses', ['enrichment_status'], unique=False)
    op.create_index(op.f('ix_businesses_industry'), 'businesses', ['industry'], unique=False)
    op.create_index(op.f('ix_businesses_lead_status'), 'businesses', ['lead_status'], unique=False)
    op.create_index(op.f('ix_businesses_normalized_domain'), 'businesses', ['normalized_domain'], unique=False)
    op.create_index(op.f('ix_businesses_normalized_name'), 'businesses', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_businesses_normalized_phone'), 'businesses', ['normalized_phone'], unique=False)
    op.create_index(op.f('ix_businesses_state'), 'businesses', ['state'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('uploaded_by', sa.String(length=120), nullable=False),
    sa.Column('column_mapping', sa.JSON(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('created_businesses', sa.Integer(), nullable=False),
    sa.Column('linked_duplicates', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('role_category', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('email_type', sa.String(length=30), nullable=True),
    sa.Column('direct_phone', sa.String(length=50), nullable=True),
    sa.Column('phone_type', sa.String(length=30), nullable=True),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('linkedin_url', sa.String(length=400), nullable=True),
    sa.Column('contact_source', sa.String(length=40), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('verified_status', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_business_id'), 'contacts', ['business_id'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('duplicate_of_existing', sa.Boolean(), nullable=False),
    sa.Column('duplicate_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_records_business_id'), 'source_records', ['business_id'], unique=False)
    op.create_index(op.f('ix_source_records_import_batch_id'), 'source_records', ['import_batch_id'], unique=False)
    op.create_table('call_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('caller_name', sa.String(length=120), nullable=False),
    sa.Column('call_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('phone_called', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('next_action', sa.String(length=300), nullable=True),
    sa.Column('callback_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_attempts_business_id'), 'call_attempts', ['business_id'], unique=False)
    op.create_index(op.f('ix_call_attempts_outcome'), 'call_attempts', ['outcome'], unique=False)
    op.create_table('call_discoveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('source_call_attempt_id', sa.Integer(), nullable=True),
    sa.Column('owner_name_discovered', sa.String(length=200), nullable=True),
    sa.Column('title_discovered', sa.String(length=200), nullable=True),
    sa.Column('direct_extension_discovered', sa.String(length=20), nullable=True),
    sa.Column('direct_number_discovered', sa.String(length=50), nullable=True),
    sa.Column('email_discovered', sa.String(length=200), nullable=True),
    sa.Column('best_callback_time', sa.String(length=200), nullable=True),
    sa.Column('transfer_instructions', sa.Text(), nullable=True),
    sa.Column('gatekeeper_name', sa.String(length=200), nullable=True),
    sa.Column('decision_maker_schedule', sa.String(length=300), nullable=True),
    sa.Column('discovered_by', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['source_call_attempt_id'], ['call_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_discoveries_business_id'), 'call_discoveries', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_discoveries_business_id'), table_name='call_discoveries')
    op.drop_table('call_discoveries')
    op.drop_index(op.f('ix_call_attempts_outcome'), table_name='call_attempts')
    op.drop_index(op.f('ix_call_attempts_business_id'), table_name='call_attempts')
    op.drop_table('call_attempts')
    op.drop_index(op.f('ix_source_records_import_batch_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_business_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_contacts_business_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_businesses_state'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_normalized_phone'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_normalized_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_normalized_domain'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_lead_status'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_industry'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_enrichment_status'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_do_not_call'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
